INSERT INTO `caracteristicaspuesto` VALUES ('30001',
'30001',
'Se solicita personal para cubrir puesto de Maestranza, 
se requiere ser mayor de 18 años, tener secundario completo y residir en la ciudad de Cordoba. 
Las tareas son de mantenimiento, orden y limpieza, de espacios comunes del edificio, 
recolección de basura y desinfección, entre otros.',
'Permanente',
'Sin experiencia previa',
'Ser mayor de Edad, Secundario completo, residir en la Ciudad de Cordoba',
'Conocimiento y manejo, de aspiradoras e hidrolavadoras.'),
('30002',
'30002',
'Se solicita personal de limpieza de caracter urgente, para cubrir puestos en Shpping Nuevo Centro.',
'Temporal',
'Sin Experiencia',
'Ser Mayor de edad, Secundario Completo, Residir en la Ciudad de Cordoba o Zonas aledañas',
'Manejo de Hidro-lavadora'),
('30003',
'30003',
'Se solicita personal de Maestranza, por la mañana, de 8 a 13 hs, para Hospital Ferreyra',
'Temporal',
'Sin Experiencia',
'Ser Mayor de edad, Secundario completo, residir en la ciudad de Cordoba',
'Cualquier conocimiento en uso de aspiradoras e Hidro-lavadoras.'),
('30004',
'30004',
'Se solicita personal para cubrir puesto de Maestranza, tareas a realizar, mantenimieto y limpieza de sectores 
de jardín y galerías de importante edificio, ubicado en zona centro.',
'Temporal',
'Sin Experiencia',
'Ser Mayor de Edad, Secundario Completo, residir en zona centro',
'Cualquier conocimiento en plomeria, electricidad y cuidado de jardínes.'),
('30005',
'30005',
'Se solicita personal para cubrir puesto de Maestranza, encargado de edificio. Tareas, 
Limpeiza de espacios comunes, recolección de basura, Informe de estado general de la unidad.',
'Permanente',
'Con Experiencia',
'Ser Mayor de Edad, Secundario complreto, residir en Ciudad de Córdoba, o localidad cercana, 
no mayor a los 20 Km.',
'Conocimientos en Plomería y Cerrajería'),
('30006',
'30006',
'Se solicira personal para cubrir puesto de Maestranza, 
Jefe de sector. Tareas: gestionar los recursos, y elemento de limpieza que reciban desde 
central. Controlar el cumplimiento de las tareas de mantenimiento, orden y limpieza, 
de los demás empleados, en los establecimientos asignados. ',
'Permanente',
'Con Experiencia',
'Ser Mayor de de Edad, Secundario Completo, residir en la Cordoba Capital, 
o en zonas aledañas, buena presencia, capacidad para trabajar bajo presión.',
'Conocimintos en uso de Excel, Sistemas de Gestión de personal en general. '),
('30007',
'30007',
'Se solicita Maestranza de caracter urgente',
'Permanente',
'Sin Experiencia',
'Mayor de edad, residir en Cordoba Capital',
'Buena presencia'),
('30008',
'30008',
'Se solicita Personal Carniceria, para cubrir puesto en importante local en el Mercado Norte.',
'Permanente',
'Con Experiencia',
'Ser Mayor de Edad, Secundario Completo, Residir en la ciudad de Cordoba',
'Buen manejo de Herraminentas de trabajo.');
